export const error = {
  id_not_found: "ID não foi encontrado",
  email_already_registered: "Email já registrado",
  cannot_create_building: "Não foi possível criar o edifício",
  invalid_credentials: "Credenciais inválidas",
  bad_request: "400",
  building_not_found: "Edifício não foi encontrado",
  generate_token_error: "Erro durante geração de token",
  user_not_registered: "Usuário não registrado",
  email_cannot_be_null: "O campo email é obrigatório",
  cannot_create_user: "Não foi possível criar o usuário",
  internal_server_error: "500",
  cannot_create_solicitation: "Não foi possível criar a solicitacao",
  role_id_not_found: "ID não foi encontrado",
  laundry_not_found: "Lavandeira não encontrada",
  cannot_create_message: "Não foi possível salvar a mensagem",
  cannot_create_event: "Não foi possível salvar o evento",
  cannot_create_hour: "Não foi possível criar o horário",
  cannot_save_image: "Não foi possível salvar a imagem",
  cannot_update_solicitation: "Não foi possível atualizar a solicitação",
  cannot_find_solicitation: "Não foi possível buscar as solicitações",
  cannot_confirm_event: "Não foi possível buscar as solicitações",
  base64_required: "O parâmetro 'base64' é obrigatório",
  building_without_user: "O predio pesquisado não possui usuários ativos",
  solicitation_type_already_registered: "O tipo de solicitação já foi cadastrado",
  cannot_create_event_with_old_date: "Não é possível criar um evento com data antiga",
  hour_limit_exceded: "Limite máximo de eventos excedidos para esse horário",
  cannot_create_event_with_same_hours: "Não é possível criar um evento com o mesmo horário de abertura e encerramento",
  quantity_limit_exceded: "Limite máximo de mudanças atingido para esse horário",
  user_not_approved: "Usuário ainda não foi aprovado",
  password_is_required: "O campo senha é obrigatório",
  email_is_required: "O campo email é obrigatório",
  password_invalid: "A senha inserida é inválida",
  invalid_refresh_token: "O token enviado é inválido",
  image_not_found: "O usuário não possui imagem",
  permission_denied: "Permissão negada",
};
