import { MigrationInterface, QueryRunner } from "typeorm";

export class createMensagensTable1602873576004 implements MigrationInterface {
  name = "createMensagensTable1602873576004";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "MENSAGEM" ("id" number GENERATED BY DEFAULT AS IDENTITY, "MENSAGEM" varchar2(255) NOT NULL, "DATA" timestamp NOT NULL, "USUARIO_ID" number, "ADMIN_ID" number, "SOLICITACAO_ID" number, CONSTRAINT "PK_2e1c36af164d01a54b4b570573f" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(`CREATE INDEX "IDX_54d112e7299dd3a8a65f39808f" ON "MENSAGEM" ("SOLICITACAO_ID")`);
    await queryRunner.query(
      `ALTER TABLE "MENSAGEM" ADD CONSTRAINT "FK_373793c1966a510aca6c4e1b3be" FOREIGN KEY ("USUARIO_ID") REFERENCES "USUARIO" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "MENSAGEM" ADD CONSTRAINT "FK_e12f76e4c046a8c551c62d50d57" FOREIGN KEY ("ADMIN_ID") REFERENCES "USUARIO_ADMINISTRADOR" ("ID")`,
    );
    await queryRunner.query(
      `ALTER TABLE "MENSAGEM" ADD CONSTRAINT "FK_54d112e7299dd3a8a65f39808fd" FOREIGN KEY ("SOLICITACAO_ID") REFERENCES "SOLICITACAO" ("ID")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "MENSAGEM" DROP CONSTRAINT "FK_54d112e7299dd3a8a65f39808fd"`);
    await queryRunner.query(`ALTER TABLE "MENSAGEM" DROP CONSTRAINT "FK_e12f76e4c046a8c551c62d50d57"`);
    await queryRunner.query(`ALTER TABLE "MENSAGEM" DROP CONSTRAINT "FK_373793c1966a510aca6c4e1b3be"`);
    await queryRunner.query(`DROP INDEX "IDX_54d112e7299dd3a8a65f39808f"`);
    await queryRunner.query(`DROP TABLE "MENSAGEM"`);
  }
}
